services:
  - type: web_service
    name: mkoba-system
    env: docker
    branch: main
    dockerfilePath: ./Dockerfile
    dockerContext: .
    envVars:
      - key: JDBC_DATABASE_URL
        value: jdbc:postgresql://dpg-d82fqhfaqgkc7394eq8g-a/m_koba
      - key: DB_USERNAME
        value: m_koba_user
      - key: DB_PASSWORD
        value: YjLcBw3aqh2x9XsBQzGqJYDYOI6o9uhG
      - key: BASE_URL
        value: https://mkoba-system1.onrender.com
